# NumPy for Numerical Data Analysis

A hands-on tour of NumPy fundamentals: array creation, inspection, indexing,
reshaping, generation functions, math & vectorized operations, boolean masking,
broadcasting, and aggregate functions.

## 0. Setup

In [1]:
import numpy as np

print("NumPy version:", np.__version__)

NumPy version: 2.4.4


## 1. Creating 1D, 2D, and 3D Arrays

NumPy arrays (`ndarray`) can hold data in any number of dimensions. We build one
example of each from Python lists.

In [2]:
# 1D array (vector)
arr_1d = np.array([10, 20, 30, 40, 50])
print("1D array:\n", arr_1d)

1D array:
 [10 20 30 40 50]


In [3]:
# 2D array (matrix)
arr_2d = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])
print("2D array:\n", arr_2d)

2D array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
# 3D array (a stack of 2 matrices, each 3x3)
arr_3d = np.array([[[1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9]],

                    [[10, 11, 12],
                     [13, 14, 15],
                     [16, 17, 18]]])
print("3D array:\n", arr_3d)

3D array:
 [[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]


## 2. Checking Array Dimensions and Data Types

Useful attributes: `ndim` (number of dimensions), `shape` (size along each axis),
`size` (total number of elements), and `dtype` (data type of elements).

In [5]:
for name, a in [("arr_1d", arr_1d), ("arr_2d", arr_2d), ("arr_3d", arr_3d)]:
    print(f"{name}: ndim={a.ndim}, shape={a.shape}, size={a.size}, dtype={a.dtype}")

arr_1d: ndim=1, shape=(5,), size=5, dtype=int64
arr_2d: ndim=2, shape=(3, 3), size=9, dtype=int64
arr_3d: ndim=3, shape=(2, 3, 3), size=18, dtype=int64


In [6]:
# Explicitly setting a dtype
float_arr = np.array([1, 2, 3], dtype=np.float64)
int_arr = np.array([1.9, 2.9, 3.9], dtype=np.int32)
print("float_arr:", float_arr, float_arr.dtype)
print("int_arr:", int_arr, int_arr.dtype)  # truncates decimals

float_arr: [1. 2. 3.] float64
int_arr: [1 2 3] int32


## 3. Indexing and Slicing

NumPy supports Python-style indexing/slicing plus multi-dimensional indexing
using comma-separated indices.

In [7]:
# 1D indexing and slicing
print("arr_1d:", arr_1d)
print("First element:", arr_1d[0])
print("Last element:", arr_1d[-1])
print("Slice [1:4]:", arr_1d[1:4])
print("Every other element:", arr_1d[::2])

arr_1d: [10 20 30 40 50]
First element: 10
Last element: 50
Slice [1:4]: [20 30 40]
Every other element: [10 30 50]


In [8]:
# 2D indexing and slicing
print("arr_2d:\n", arr_2d)
print("Element at row 1, col 2:", arr_2d[1, 2])
print("Entire row 0:", arr_2d[0, :])
print("Entire column 1:", arr_2d[:, 1])
print("Sub-matrix (rows 0-1, cols 1-2):\n", arr_2d[0:2, 1:3])

arr_2d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Element at row 1, col 2: 6
Entire row 0: [1 2 3]
Entire column 1: [2 5 8]
Sub-matrix (rows 0-1, cols 1-2):
 [[2 3]
 [5 6]]


In [9]:
# 3D indexing and slicing
print("arr_3d shape:", arr_3d.shape)
print("First matrix (depth 0):\n", arr_3d[0])
print("Element at [1, 2, 0]:", arr_3d[1, 2, 0])
print("All depths, row 0, all cols:\n", arr_3d[:, 0, :])

arr_3d shape: (2, 3, 3)
First matrix (depth 0):
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Element at [1, 2, 0]: 16
All depths, row 0, all cols:
 [[ 1  2  3]
 [10 11 12]]


## 4. Reshaping Arrays

`reshape()` returns a new view with a different shape (same total elements).
`ravel()`/`flatten()` collapse an array back to 1D.

In [10]:
base = np.arange(1, 13)  # 1D array with 12 elements
print("Original:", base)

reshaped_2d = base.reshape(3, 4)
print("Reshaped to (3,4):\n", reshaped_2d)

reshaped_3d = base.reshape(2, 3, 2)
print("Reshaped to (2,3,2):\n", reshaped_3d)

flattened = reshaped_2d.flatten()
print("Flattened back to 1D:", flattened)

# -1 lets NumPy infer that dimension automatically
auto_reshape = base.reshape(4, -1)
print("Reshaped with -1 inferred -> (4,-1):\n", auto_reshape)

Original: [ 1  2  3  4  5  6  7  8  9 10 11 12]
Reshaped to (3,4):
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Reshaped to (2,3,2):
 [[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
Flattened back to 1D: [ 1  2  3  4  5  6  7  8  9 10 11 12]
Reshaped with -1 inferred -> (4,-1):
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


## 5. Generating Arrays with Built-in Functions

Common ways to quickly generate arrays without manually typing values.

In [11]:
zeros_arr = np.zeros((2, 3))
print("zeros((2,3)):\n", zeros_arr)

zeros((2,3)):
 [[0. 0. 0.]
 [0. 0. 0.]]


In [12]:
ones_arr = np.ones((3, 2), dtype=int)
print("ones((3,2), dtype=int):\n", ones_arr)

ones((3,2), dtype=int):
 [[1 1]
 [1 1]
 [1 1]]


In [13]:
identity_arr = np.eye(4)
print("Identity matrix eye(4):\n", identity_arr)

Identity matrix eye(4):
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [14]:
arange_arr = np.arange(0, 20, 2)  # start, stop (exclusive), step
print("arange(0, 20, 2):", arange_arr)

arange(0, 20, 2): [ 0  2  4  6  8 10 12 14 16 18]


In [15]:
linspace_arr = np.linspace(0, 1, 5)  # start, stop (inclusive), num points
print("linspace(0, 1, 5):", linspace_arr)

linspace(0, 1, 5): [0.   0.25 0.5  0.75 1.  ]


In [16]:
full_arr = np.full((2, 2), 7)
random_arr = np.random.default_rng(42).integers(0, 10, size=(2, 3))
print("full((2,2), 7):\n", full_arr)
print("random integers (2,3):\n", random_arr)

full((2,2), 7):
 [[7 7]
 [7 7]]
random integers (2,3):
 [[0 7 6]
 [4 4 8]]


## 6. Mathematical and Vectorized Operations

NumPy applies operations element-wise ("vectorized") without explicit Python
loops, which is both concise and fast.

In [17]:
a = np.array([1, 2, 3, 4])
b = np.array([10, 20, 30, 40])

print("a + b =", a + b)
print("a - b =", a - b)
print("a * b =", a * b)
print("b / a =", b / a)
print("a ** 2 =", a ** 2)
print("sqrt(a) =", np.sqrt(a))
print("exp(a) =", np.exp(a))
print("log(b) =", np.log(b))

a + b = [11 22 33 44]
a - b = [ -9 -18 -27 -36]
a * b = [ 10  40  90 160]
b / a = [10. 10. 10. 10.]
a ** 2 = [ 1  4  9 16]
sqrt(a) = [1.         1.41421356 1.73205081 2.        ]
exp(a) = [ 2.71828183  7.3890561  20.08553692 54.59815003]
log(b) = [2.30258509 2.99573227 3.40119738 3.68887945]


In [18]:
# Matrix operations
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([[5, 6], [7, 8]])

print("Element-wise multiply:\n", m1 * m2)
print("Matrix (dot) product:\n", m1 @ m2)
print("Transpose of m1:\n", m1.T)

Element-wise multiply:
 [[ 5 12]
 [21 32]]
Matrix (dot) product:
 [[19 22]
 [43 50]]
Transpose of m1:
 [[1 3]
 [2 4]]


## 7. Boolean Masking

Comparisons on arrays produce boolean arrays, which can then be used to filter
or selectively modify elements no explicit loop needed.

In [19]:
data = np.array([4, 15, 8, 23, 42, 3, 17, 9])
mask = data > 10
print("data:", data)
print("mask (data > 10):", mask)
print("Filtered values (data[mask]):", data[mask])

data: [ 4 15  8 23 42  3 17  9]
mask (data > 10): [False  True False  True  True False  True False]
Filtered values (data[mask]): [15 23 42 17]


In [20]:
# Combine conditions with & and |
mask_range = (data > 5) & (data < 20)
print("Values between 5 and 20:", data[mask_range])

# Modify values in place using a mask
data_copy = data.copy()
data_copy[data_copy > 10] = 0
print("After zeroing values > 10:", data_copy)

Values between 5 and 20: [15  8 17  9]
After zeroing values > 10: [4 0 8 0 0 3 0 9]


## 8. Broadcasting

Broadcasting lets NumPy perform arithmetic on arrays of different (but
compatible) shapes by automatically expanding the smaller array.

In [21]:
# Scalar broadcast over an array
matrix = np.array([[1, 2, 3],
                    [4, 5, 6]])
print("matrix + 10:\n", matrix + 10)

matrix + 10:
 [[11 12 13]
 [14 15 16]]


In [22]:
# 1D array broadcast across each row of a 2D array
row_vector = np.array([100, 200, 300])
print("matrix shape:", matrix.shape, "| row_vector shape:", row_vector.shape)
print("matrix + row_vector:\n", matrix + row_vector)

matrix shape: (2, 3) | row_vector shape: (3,)
matrix + row_vector:
 [[101 202 303]
 [104 205 306]]


In [23]:
# Column vector broadcast across each column
col_vector = np.array([[1], [2]])
print("matrix shape:", matrix.shape, "| col_vector shape:", col_vector.shape)
print("matrix + col_vector:\n", matrix + col_vector)

matrix shape: (2, 3) | col_vector shape: (2, 1)
matrix + col_vector:
 [[2 3 4]
 [6 7 8]]


## 9. Aggregate Functions

Functions like `sum()`, `mean()`, `min()`, `max()`, and `median()` reduce an
array to summary statistics either over the whole array or along a chosen axis.

In [24]:
values = np.array([[5, 10, 15],
                    [20, 25, 30]])
print("values:\n", values)

print("Sum (all):", values.sum())
print("Mean (all):", values.mean())
print("Min (all):", values.min())
print("Max (all):", values.max())
print("Median (all):", np.median(values))
print("Std Dev (all):", values.std())

values:
 [[ 5 10 15]
 [20 25 30]]
Sum (all): 105
Mean (all): 17.5
Min (all): 5
Max (all): 30


Median (all): 17.5
Std Dev (all): 8.539125638299666


In [25]:
# Axis-wise aggregation: axis=0 -> down columns, axis=1 -> across rows
print("Sum per column (axis=0):", values.sum(axis=0))
print("Sum per row (axis=1):", values.sum(axis=1))
print("Mean per column (axis=0):", values.mean(axis=0))
print("Max per row (axis=1):", values.max(axis=1))

Sum per column (axis=0): [25 35 45]
Sum per row (axis=1): [30 75]
Mean per column (axis=0): [12.5 17.5 22.5]
Max per row (axis=1): [15 30]


## 10. Summary

This notebook covered:
- Creating 1D, 2D, and 3D arrays
- Inspecting dimensions, shape, size, and dtype
- Indexing and slicing across dimensions
- Reshaping and flattening arrays
- Generating arrays with `zeros()`, `ones()`, `eye()`, `arange()`, `linspace()`, `full()`, and random generators
- Element-wise math, vectorized operations, and matrix multiplication
- Boolean masking for filtering and conditional updates
- Broadcasting rules for mismatched shapes
- Aggregate functions (`sum`, `mean`, `min`, `max`, `median`, `std`) overall and along axes

NumPy's vectorized, array-oriented approach is the foundation for most of the
Python numerical/data-science stack (pandas, scikit-learn, PyTorch, etc.).